kumuluzee:
  name: rso1920-fileDownloader
  version: 1.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  server:
    base-url: http://localhost:8079/
    http:
      port: 8079
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /v1/download/file/*
        status-codes: "200, 500, 400"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="cfffe2f5-63d9-4c32-a175-636585889410-ls.logit.io"
                              port="21975" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'