kumuluzee:
  name: rso1920-fileDownloader
  version: 1.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  server:
    base-url: http://localhost:8079/
    http:
      port: 8079
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /v1/download/file/*
        status-codes: "200, 500"