apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-file-downloader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-file-downloader
  template:
    metadata:
      labels:
        app: rso1920-file-downloader
    spec:
      containers:
        - image: rso1920/filedownloader:latest
          name: rso1920-file-downloader
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://10.28.5.5:8079
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
          ports:
            - containerPort: 8079
              name: file-downloader
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: file-downloader
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: file-downloader
            initialDelaySeconds: 60
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-file-downloader
spec:
  type: ClusterIP
  ports:
    - port: 8079
      protocol: TCP
      targetPort: file-downloader
  selector:
    app: rso1920-file-downloader
